

import "./globals.css";


export const metadata = {
  title: "ai captions generator",
  keywords: "ai, captions, generator, image captions, social media",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
       
            {children}

     
       
      </body>
    </html>
  );
}
